docker build -t social-login-server:latest \
--build-arg SOCIAL_LOGIN_GOOGLE_CLIENT_ID=$SOCIAL_LOGIN_GOOGLE_CLIENT_ID \
--build-arg SOCIAL_LOGIN_FACEBOOK_APP_ID=$SOCIAL_LOGIN_FACEBOOK_APP_ID \
--build-arg SOCIAL_LOGIN_FACEBOOK_APP_SECRET=$SOCIAL_LOGIN_FACEBOOK_APP_SECRET \
.
