version: '3'

services:
  server:
    image: social-login-server
    container_name: social-login-server-node
    ports:
      - 9000:9000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.24
    command: mysqld
    container_name: social-login-server-mysql
    ports:
      - 33306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=luanpass
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql/init:/docker-entrypoint-initdb.d
